
CFLAGS := -Wall -O3 -ffast-math -msse -msse2 -mfpmath=sse -fPIC -I../vamp-plugin-sdk-bin/vamp-plugin-sdk-2.10.0-binaries-amd64-linux/

#CFLAGS := -g -fPIC -I../vamp-plugin-sdk-bin/vamp-plugin-sdk-2.10.0-binaries-amd64-linux

CXXFLAGS := $(CFLAGS) -std=c++11

PLUGIN_LDFLAGS := -shared -Wl,--version-script=vamp/vamp-plugin.map

VAMPSDK_DIR := ../vamp-plugin-sdk-bin/vamp-plugin-sdk-2.10.0-binaries-amd64-linux

PLUGIN_EXT := .so

include Makefile.inc

